vim.opt.formatoptions:append({ t = true })
vim.opt.wrap = true
vim.opt.linebreak = true
vim.opt.textwidth = 40
vim.opt.wrapmargin = 0
vim.opt.foldlevel = 999
vim.opt.colorcolumn = "0"
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
